AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Struts AWS Lambda Support Plugin Example - 1.4.2
Globals:
  Api:
    EndpointConfiguration: REGIONAL

Resources:
  StrutsLambdaSupportExampleFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.amazonaws.serverless.proxy.struts.StrutsLambdaHandler::handleRequest
      Runtime: java8
      CodeUri: target/struts2-aws-lambda-support-example-1.4.2-lambda.zip
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 30
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  StrutsLambdaSupportExampleApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/data/order.json'
    Export:
      Name: StrutsLambdaSupportExample
